name: Report Coverage

on: [push, pull_request]

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: microsoft/playwright-github-action@v1
      - run: npm install -g yarn
      - run: yarn install --ignore-scripts --frozen-lockfile
      - run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
